export const SET_PROFILE="SET_PROFILE";
export const SET_ACCOUNT="SET_ACCOUNT";


export const SET_MYITEMS="SET_MYITEMS";

export const SET_MYITEMSONSALE="SET_MYITEMSONSALE";

export const SET_SALEITEMS="SET_SALEITEMS";

export const SET_AUCTIONITEMS="SET_AUCTIONITEMS";
